# command line: main.py --config config/uav-csv2/default.yaml --work-dir work_dir/uav2/skmixf_k2 --device 2 3

base_lr: 0.2
batch_size: 128
config: config/uav-csv2/default.yaml
device:
- 2
- 3
eval_interval: 5
feeder: feeders.feeder_uav.Feeder
ignore_weights: []
log_interval: 100
model: model.ske_mixfk2.Model
model_args:
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 155
  num_person: 2
  num_point: 17
model_saved_name: ''
nesterov: true
num_epoch: 70
num_worker: 32
optimizer: SGD
phase: train
print_log: true
save_epoch: 30
save_interval: 1
save_score: True
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 50
test_batch_size: 128
test_feeder_args:
  bone: false
  data_path: /data/yinbaiqiao/ICMEW2024-Track10-main/Model_inference/Mix_GCN/dataset/save_2d_pose/V2.npz
  debug: false
  p_interval:
  - 0.95
  split: test
  vel: false
  window_size: 64
train_feeder_args:
  bone: false
  data_path: /data/yinbaiqiao/ICMEW2024-Track10-main/Model_inference/Mix_GCN/dataset/save_2d_pose/V2.npz
  debug: false
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: false
  random_shift: false
  split: train
  vel: false
  window_size: 64
warm_up_epoch: 5
weight_decay: 0.0005
weights: null
work_dir:  ./output/skmixf__V2_k2
